name: tests

on:
  push:
    branches:
      - main
      - master
      - feature/*
      - hotfix/*
      - bugfix/*
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Run tests
        run: go test ./...
